baseURL = 'https://ajency.github.io/cibil-dashboard-paid/'
languageCode = 'en-us'
title = 'Cibil Dashboard'
theme = 'dashboard'
publishDir =  'docs'

[markup.goldmark.parser.attribute]
block = true
title = true

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10